fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "darn"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["Berkeley Mono"]
# normal = ["RecMonoDuotone Nerd Font Mono"]
# normal = "FiraCode Nerd Font Mono"
edging = "subpixelantialias"
hinting = "slight"
# edging = "alias"
size = 12


[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"
