[Appearance]
color_scheme_path=/home/sthom/.config/qt5ct/colors/noctalia.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Berkeley Mono Variable,11,-1,5,50,0,0,0,0,0"
general="Berkeley Mono Variable,11,-1,5,50,0,0,0,0,0"
