[Appearance]
color_scheme_path=/home/sthom/.config/qt6ct/colors/noctalia.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Berkeley Mono Variable,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
general="Berkeley Mono Variable,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\xff\0\0\x5\xe7\0\0\0\0\0\0\0\0\0\0\a\xff\0\0\x5\xe7\0\0\0\0\x2\0\0\0\x14\0\0\0\0\0\0\0\0\0\0\0\a\xff\0\0\x5\xe7)
