$mainMonitor = DP-1
$secondaryMonitor = HDMI-A-1

monitor = eDP-1,3840x2400@60,0x0,1.5
# monitor = HDMI-A-1, modeline 594.00 5120 5168 5200 5280 2160 2163 2173 2250 +hsync -vsync, -640x-2400, 1
monitor = HDMI-A-1, modeline 594.00 5120 5168 5200 5280 2160 2163 2173 2250 +hsync -vsync, -640x-2160, 1

device {
    name = elan0683:00-04f3:320b-touchpad
    sensitivity = +0.5
}

input {
    touchpad {
        scroll_factor = 1.0
    }
}

exec-once = [workspace 1 silent] firefox



workspace = name:laptop, monitor:eDP-1, default:true
workspace = 1, monitor:HDMI-A-1, default:true # , on-created-empty: firefox # , persistent:true

workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1

bind = SUPER, code:49, workspace, name:laptop
bind = SUPER SHIFT, code:49, movetoworkspacesilent, name:laptop

bind = SUPER, A, exec, dms ipc plugins toggle realtimeWhisper
# bindr = SUPER, A, execr, fish -c "sleep 1; hyprvoice toggle"

