-- Hyprland Lua entrypoint.
--
-- Keep compositor options in the single config call below. The required modules
-- register behavior that uses dedicated APIs: env vars, curves, animations,
-- autostart hooks, binds, gestures, and rules.

hl.config({
	autogenerated = false,

	-- Keyboard, pointer, and touchpad defaults from hyprland.conf.
	input = {
		kb_layout = "us",
		numlock_by_default = true,
		repeat_rate = 60,
		repeat_delay = 200,
		follow_mouse = 2,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
			drag_lock = true,
		},
	},

	-- Core compositor behavior.
	general = {
		gaps_in = 16,
		gaps_out = 32,
		border_size = 0,
		col = {
			-- Current DMS colors. The previous gradient borders are kept in git
			-- history if you want them back later.
			active_border = "rgb(a6c8ff)",
			inactive_border = "rgb(8c919c)",
		},
		layout = "master",
		allow_tearing = false,
	},

	-- Layout tuning.
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
		special_scale_factor = 0.95,
		new_status = "slave",
		new_on_top = false,
		orientation = "center",
		slave_count_for_center_master = 2,
	},
	scrolling = {
		direction = "down",
	},

	-- Session and compositor miscellany.
	misc = {
		force_default_wallpaper = 0,
		key_press_enables_dpms = true,
		mouse_move_enables_dpms = true,
		disable_splash_rendering = true,
	},

	-- Cursor and NVIDIA workaround settings from modules/env.conf.
	cursor = {
		no_hardware_cursors = true,
	},

	-- Shared bind behavior from modules/binds.conf.
	binds = {
		scroll_event_delay = 50,
	},

	-- Decoration and opacity settings from modules/looks.conf.
	decoration = {
		rounding = 16,
		rounding_power = 4.0,
		blur = {
			enabled = true,
			size = 12,
			passes = 3,
			ignore_opacity = true,
			new_optimizations = true,
			xray = true,
		},
		shadow = {
			enabled = true,
			range = 36,
			render_power = 3,
			color = "rgba(000000aa)",
			offset = { 0, 1 },
		},
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		fullscreen_opacity = 1.0,
		dim_special = 0.7,
		dim_inactive = false,
		dim_strength = 0.2,
		dim_around = 0.5,
	},
	animations = {
		enabled = true,
	},

	-- Current DMS group colors from dms/colors.lua.
	group = {
		col = {
			border_active = "rgb(a6c8ff)",
			border_inactive = "rgb(8c919c)",
			border_locked_active = "rgb(ffb4ab)",
			border_locked_inactive = "rgb(8c919c)",
		},
		groupbar = {
			col = {
				active = "rgb(a6c8ff)",
				inactive = "rgb(8c919c)",
				locked_active = "rgb(ffb4ab)",
				locked_inactive = "rgb(8c919c)",
			},
		},
	},

	-- Plugin config from modules/plugins.conf. Keep disabled for parity with
	-- the old commented source line.
	-- plugin = {
	-- 	hyprwinwrap = {
	-- 		class = "kitty-bg",
	-- 	},
	-- },
})

-- Per-device keyboard config uses the dedicated device API.
hl.device({
	name = "ydotoold-virtual-device",
	kb_layout = "us",
	kb_variant = "",
	kb_options = "",
})

local device = require("device")

require("modules.env")
require("modules.looks")
require("modules.exec")
require("modules.binds")
require("modules.gestures")
require("modules.rules").setup(device)

-- DMS colors are copied into the config table above so this file owns the only
-- active config call. Re-enable this only if you want DMS to apply its own
-- generated config call again.
-- require("dms.colors")
--
-- Keep plugins disabled until you want the old commented plugin config active.
-- require("modules.plugins")
