-- Hyprland Lua entrypoint.
--
-- Keep compositor options in the single config call below. The required modules
-- register behavior that uses dedicated APIs: env vars, curves, animations,
-- autostart hooks, binds, gestures, and rules.

local function with_alpha(rgb, alpha)
	local hex = assert(rgb:match("^rgb%((%x%x%x%x%x%x)%)$"), "invalid rgb color")
	local alpha_byte = math.floor(math.max(0, math.min(1, alpha)) * 255 + 0.5)

	return ("rgba(%s%02x)"):format(hex, alpha_byte)
end

hl.config({
	autogenerated = false,

	-- Keyboard, pointer, and touchpad defaults from hyprland.conf.
	input = {
		kb_layout = "us",
		numlock_by_default = true,
		repeat_rate = 60,
		repeat_delay = 200,
		follow_mouse = 2,
		float_switch_override_focus = 0,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
			drag_lock = true,
		},
	},

	-- Core compositor behavior.
	general = {
		gaps_in = 12,
		gaps_out = 24,
		float_gaps = -1,
		border_size = 2,
		col = {
			-- Fallback colors. Generated noctalia.lua overrides these below.
			active_border = "rgb(b6c7e9)",
			inactive_border = "rgb(8f9098)",
		},
		layout = "lua:center_columns",
		allow_tearing = false,
		snap = {
			enabled = true,
		},
	},

	-- Layout tuning.
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
		special_scale_factor = 0.95,
		new_status = "slave",
		new_on_top = false,
		orientation = "center",
		slave_count_for_center_master = 2,
	},
	scrolling = {
		direction = "down",
	},

	-- Session and compositor miscellany.
	misc = {
		force_default_wallpaper = 0,
		key_press_enables_dpms = true,
		mouse_move_enables_dpms = true,
		disable_splash_rendering = true,
	},

	-- Let Hyprland choose hardware cursors based on the active driver.
	cursor = {
		no_hardware_cursors = 2,
	},
	xwayland = {
		force_zero_scaling = true,
	},

	-- Shared bind behavior from modules/binds.conf.
	binds = {
		scroll_event_delay = 50,
	},

	-- Decoration and opacity settings from modules/looks.conf.
	decoration = {
		-- rounding = 16,
		rounding = 0,
		rounding_power = 4.0,
		blur = {
			enabled = true,
			size = 12,
			passes = 3,
			ignore_opacity = true,
			new_optimizations = true,
			xray = true,
		},
		shadow = {
			enabled = true,
			range = 64,
			render_power = 4,
			color = "rgba(000000aa)",
			color_inactive = "rgba(000000aa)",
			offset = { 0, 1 },
		},
		glow = {
			enabled = true,
			range = 8,
			render_power = 4,
			-- color = "rgba(b6c7e955)",
			-- color = "rgba(00000055)",
			color = "rgba(00000000)",
			-- color_inactive = "rgba(8f909800)",
			color_inactive = "rgba(00000088)",
		},
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		fullscreen_opacity = 1.0,
		dim_special = 0.7,
		dim_inactive = false,
		dim_strength = 0.2,
		dim_around = 0.5,
	},
	animations = {
		enabled = true,
	},

	-- Fallback DMS group colors. Generated dms/colors.lua may override these.
	group = {
		col = {
			border_active = "rgb(b6c7e9)",
			border_inactive = "rgb(8f9098)",
			border_locked_active = "rgb(ffb4ab)",
			border_locked_inactive = "rgb(8f9098)",
		},
		groupbar = {
			col = {
				active = "rgb(b6c7e9)",
				inactive = "rgb(8f9098)",
				locked_active = "rgb(ffb4ab)",
				locked_inactive = "rgb(8f9098)",
			},
		},
	},

	-- Plugin config from modules/plugins.conf. Keep disabled for parity with
	-- the old commented source line.
	-- plugin = {
	-- 	hyprwinwrap = {
	-- 		class = "kitty-bg",
	-- 	},
	-- },
})

-- Per-device keyboard config uses the dedicated device API.
hl.device({
	name = "ydotoold-virtual-device",
	kb_layout = "us",
	kb_variant = "",
	kb_options = "",
})

require("modules.env")
require("modules.looks")
require("modules.exec")
require("modules.layouts")

local device = require("device")

require("modules.binds")
require("modules.lid").setup(device)
require("modules.gestures")
require("modules.rules").setup(device)

-- Generated by Noctalia's Hyprland color template.
local noctalia = require("noctalia")

-- Example: color = with_alpha(noctalia.colors.primary, 0.5)
hl.config({
	decoration = {
		glow = {
			color = with_alpha(noctalia.colors.primary, 0.3),
			color_inactive = with_alpha(noctalia.colors.surface, 0.1),
		},
	},
})

noctalia.apply_theme()

hl.config({

	general = {
		col = {
			active_border = with_alpha(noctalia.colors.secondary, 1.0),
			inactive_border = with_alpha(noctalia.colors.surface, 1.0),
		},
	},
})

-- Keep plugins disabled until you want the old commented plugin config active.
-- require("modules.plugins")
