"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[user]
name = "Spencer"
email = "sthompson.dev@outlook.com"

[git]
push = "origin"
